example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json
from mywatchlist.views import show_html

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('html/', show_html, name='show_html'),
] 

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path("delete-task/<int:id>", delete_task, name="delete_task"),
    path("update-finished/<int:id>", update_finished, name="update_finished"),
    path('json/', show_json, name='show_json'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchListItem(models.Model):
    watched = models.CharField(max_length=255)
    title = models.TextField()
    rating = models.FloatField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_catalog(request):
    data_item_catalog = CatalogItem.objects.all()
    context = {
    'list_barang': data_item_catalog,
    'name': 'Nafis Azizi Riza',
    'npm' : '2106658843'
}
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchListItem
from django.http import HttpResponse
from django.core import serializers

def show_watchlist(request):
    data_watchlist_item = MyWatchListItem.objects.all()
    not_yet = 0
    watched = 0
    mess = ""
    for movies in data_watchlist_item:
        if movies.watched:
            watched +=1
        else:
            not_yet += 1
    if watched >= not_yet:
        mess = "Congratulations, you have watched a lot of movies!"
    else:
        mess  = "Woah, you need to watch more movies!"
    context = {
        'list_item': data_watchlist_item,
        'name' : 'Nafis Azizi Riza',
        'npm' : 2106658843,
        'mess' : mess
    }
    return render(request, "mywatchlist.html", context)

def show_html(request):
    data_watchlist_item = MyWatchListItem.objects.all()
    not_yet = 0
    watched = 0
    mess = ""
    for movies in data_watchlist_item:
        if movies.watched:
            watched +=1
        else:
            not_yet += 1
    if watched >= not_yet:
        mess = "Congratulations, you have watched a lot of movies!"
    else:
        mess  = "Woah, you need to watch more movies!"
    context = {
        'list_item': data_watchlist_item,
        'name' : 'Nafis Azizi Riza',
        'npm' : 2106658843,
        'mess' : mess
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchListItem.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchListItem.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
from todolist.models import Task
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todolist_data = Task.objects.filter(user=request.user)

    not_yet = 0
    for task in todolist_data:
        if not task.is_finished:
            not_yet +=1

    if not_yet == 0 and todolist_data is not None:
        mess = f"Congratulations, you've done all the tasks"
    elif not_yet > 0:
        mess  = f"You have {not_yet} unfinished tasks"

    context = {"todolist": todolist_data, 
                "username": request.user,
                "mess": mess}
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # login first
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url="/todolist/login/")
def create_task(request):
    context = {"username": request.user}
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        Task.objects.create(
            user=request.user,
            title=title,
            description=description,
            date=datetime.datetime.today(),
        )
        return HttpResponseRedirect(reverse("todolist:show_todolist"))
    return render(request, "create_task.html", context)

@login_required(login_url="/todolist/login/")
def delete_task(request, id):
    task = Task.objects.get(user=request.user, id=id)
    task.delete()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))

@login_required(login_url="/todolist/login/")
def update_finished(request, id):
    task = Task.objects.get(user=request.user, id=id)
    task.is_finished = not task.is_finished
    task.save(update_fields=["is_finished"])
    return HttpResponseRedirect(reverse("todolist:show_todolist"))

@login_required(login_url="/todolist/login/")
def show_json(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{name}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1 style="text-align: center">👹 Assignment 3 PBP/PBD 👹</h1>

  <h5 style="text-align: center">Name: </h5>
  <p style="text-align: center">{{name}}</p>

  <h5 style="text-align: center">Student ID: </h5>
  <p style="text-align: center">{{npm}}</p>

  <h2 style="text-align: center">{{mess}}</h2>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% for item in list_item %}
    <tr>
        <th>{{item.watched}}</th>
        <th>{{item.title}}</th>
        <th>{{item.rating}}</th>
        <th>{{item.release_date}}</th>
        <th>{{item.review}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends "base.html" %}
{% block content %}

<nav class="navbar navbar-expand-lg bg-light p-3" style="padding: 16px;" >

  <div class="container-fluid">
      <a class="navbar-brand" href="#">MyWishlist</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'todolist:show_todolist' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'todolist:create_task' %}">New Task</a>
            </li>
          </ul>
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="#">{{username}}</a>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-primary">
                <a class="text-decoration-none text-white" href="{% url 'todolist:logout' %}">Logout</a>
            </button>
            </li>
          </ul>
      </div>
  </div>
</nav>

<br>
<h3 class="text-center">Add New Task</h3>

<div class="div mx-5">
  <form method="post">
    {% csrf_token %}
    <table class="table table-striped table-hover table table-bordered px-5">
      <tr>
        <td>Title: </td>
        <td><input type="text" name="title" placeholder="Fill todo" class="form-control"></td>
      </tr>
            
      <tr>
        <td>Description: </td>
        <td><input type="text" name="description" placeholder="fill description" class="form-control"></td>
      </tr>
    </table>
    <!-- <button type="submit">Create Task</button> -->
    <div class="div d-flex justify-content-center">
      <button type="submit" class="btn btn-primary">
        <a class="text-decoration-none text-white">Create Task</a>
    </button>
    </div>
  </form>
</div>

<!-- <form method="post">
    {% csrf_token %}

    <table>
        <tr>
            <td>Title: </td>
            <td><input type="text" name="title" placeholder="Fill todo" class="form-control"></td>
        </tr>
                
        <tr>
            <td>Description: </td>
            <td><input type="text" name="description" placeholder="fill description" class="form-control"></td>
        </tr>
    </table>

    <br>
    <button type="submit">Create Task</button>
</form> -->

{% endblock %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
  <div class = "login bg-primary rounded-4 p-4">

    <h1 class="text-white">Login</h1>
    <form method="POST" action="">
      {% csrf_token %}
              
        <div class="form-group first">
          <label for="username" class="text-white">Username</label>
          <input type="text" class="form-control" placeholder="enter your username" name="username">
        </div>
        <div class="form-group last my-3">
          <label for="password" class="text-white">Password</label>
          <input type="password" class="form-control" placeholder="enter your password" name="password">
        </div>
        <div class="div text-white">
          Don't have an account? <a class="text-white" href="{% url 'todolist:register' %}">Create Account</a>
        </div>
        <div class="div d-flex justify-content-center mt-3">
          <input type="submit" value="Login" class="btn btn-outline-light">
        </div>
    </form>
  
    {% if messages %}
      <ul>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}     
            
  </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
  <div class = "login bg-primary rounded-4 m-5 p-4 text-white">

    <h1>Register</h1>

      <form method="POST">  
        {% csrf_token %}  
        <table>  
            {{ form.as_table }}  
            <tr>
                <td></td>
                <td>Already have an account? <a class="text-white" href="{% url 'todolist:login' %}">Login here</a></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Register" class="btn btn-block btn-outline-light"></td>
            </tr>  
        </table>  
    </form>
    
    {% if messages %}
      <ul>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}      
            
  </div>
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

<style>
  .card:hover{
    transform: scale(1.05);
    box-shadow: 0 10px 20px rgba(0, 0, 0, .12), 0 4px 8px rgba(0, 0, 0, .06);
  }
</style>

<nav class="navbar navbar-expand-lg bg-light p-3" style="padding: 16px;" >

  <div class="container-fluid">
      <a class="navbar-brand" href="#">MyTodolist</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'todolist:show_todolist' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">New Task</a>
            </li>
          </ul>
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="#">{{username}}</a>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-primary">
                <a class="text-decoration-none text-white" href="{% url 'todolist:logout' %}">Logout</a>
            </button>
            </li>
          </ul>
      </div>
  </div>
</nav>

<!-- <div class="div m-4 d-flex justify-content-center">
  <h4>
    {{mess}}
  </h4>
</div> -->

<br>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Create New Task</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" id="formTask">
          {% csrf_token %}
          <table class="table table-striped table-hover table table-bordered px-5">
            <tr>
              <td>Title: </td>
              <td><input type="text" name="title" placeholder="Fill todo" class="form-control"></td>
            </tr>
                  
            <tr>
              <td>Description: </td>
              <td><input type="text" name="description" placeholder="Fill description" class="form-control"></td>
            </tr>
          </table>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" id ="buttonTask" data-bs-dismiss="modal" class="btn btn-primary">Add Task</button>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row row-cols-1 row-cols-md-3 g-4 mx-5" id="cardcontainer">
  
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function()  {
    refreshTodolist();
  });

  async function getTodolist() {
      return fetch("{% url 'todolist:show_json' %}").then((res) => res.json())
    }
  
  async function refreshTodolist() {
        document.getElementById("cardcontainer").innerHTML = ""
        const todolist = await getTodolist()
        let htmlString = ``
        todolist.forEach((item) => {
          const bg_type = item.fields.is_finished ? "primary" : "danger"
          const status = item.fields.is_finished ? "FINISHED" : "NOT YET"
          htmlString += `
          <div class="col">
            <div class="card">
              <div class="card-header bg-${bg_type} text-white">
                <div class="row ">
                  <div class="col">
                    ${item.fields.date}
                  </div>
                  <div class="col font-weight-bold" align="right">
                    ${status}
                  </div>
                </div>
              </div>
              <div class="card-body">
                <h5 class="card-title">${item.fields.title}</h5>
                <p class="card-text">${item.fields.description}</p>
                <div class="row">
                  <div class="col">
                    <button class="btn btn-primary" onclick="updateTask(${item.pk})">Change Status</button>
                  </div>
                  <div class="col d-flex justify-content-end">
                    <button class="btn btn-primary" onclick="deleteTask(${item.pk})">Delete</button>
                  </div>
                </div>
              </div>
            </div>
          </div>`
        })
        document.getElementById("cardcontainer").innerHTML = htmlString
  }
  
  function addTodolist() {
    fetch("{% url 'todolist:create_task' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#formTask'))
      }).then(refreshTodolist)
    return false
  }

  function deleteTask(val) {
    console.log(111);
    fetch("{% url 'todolist:delete_task' 0 %}".replace("0", val)).then(refreshTodolist)
  }

  function updateTask(val) {
    console.log(111);
    fetch("{% url 'todolist:update_finished' 0 %}".replace("0", val)).then(refreshTodolist)
  }
  
  document.getElementById("buttonTask").onclick = addTodolist
  refreshTodolist()
  
</script>

{% endblock content %}